import React from 'react';
import { FortuneResponse, TreeState } from '../types';
import { X, Sparkles, Gem, Snowflake, RefreshCw } from 'lucide-react';

interface OverlayProps {
  loading: boolean;
  fortune: FortuneResponse | null;
  onClose: () => void;
  showIntro: boolean;
  onStart: () => void;
  treeState: TreeState;
  toggleTreeState: () => void;
}

export const Overlay: React.FC<OverlayProps> = ({ 
  loading, 
  fortune, 
  onClose, 
  showIntro,
  onStart,
  treeState,
  toggleTreeState
}) => {
  if (showIntro) {
    return (
      <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm text-center">
        <div className="max-w-2xl p-12 border-2 border-luxury-gold bg-luxury-black/90 shadow-[0_0_50px_rgba(197,160,89,0.3)]">
          <h1 className="font-serif text-5xl md:text-7xl text-luxury-gold mb-6 uppercase tracking-widest drop-shadow-lg">
            Grand Luxury
            <br />
            <span className="text-3xl md:text-5xl text-white">Christmas</span>
          </h1>
          <p className="text-gray-300 mb-8 font-sans text-lg leading-relaxed">
            Experience the holidays like a billionaire. Click on the golden ornaments to receive a bespoke fortune generated by artificial intelligence.
          </p>
          <button 
            onClick={onStart}
            className="group relative px-8 py-4 bg-luxury-gold text-luxury-black font-bold uppercase tracking-wider overflow-hidden hover:bg-white transition-all duration-300"
          >
            <span className="relative z-10 flex items-center gap-2">
              Enter The Hall <Sparkles className="w-4 h-4" />
            </span>
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="absolute inset-0 z-40 pointer-events-none">
      {/* Header */}
      <div className="absolute top-0 left-0 w-full p-6 flex justify-between items-start pointer-events-auto">
        <div className="text-luxury-gold font-serif tracking-widest text-sm md:text-base border-b border-luxury-gold pb-1">
          TRUMP-STYLE LUXURY EDITION
        </div>
        
        {/* Toggle Button */}
        <button 
            onClick={toggleTreeState}
            className="ml-auto flex items-center gap-2 px-4 py-2 border border-luxury-gold text-luxury-gold hover:bg-luxury-gold hover:text-luxury-black transition-all duration-300 font-serif text-sm tracking-wider"
        >
            {treeState === 'FORMED' ? (
                <>
                    <Snowflake size={16} /> DECONSTRUCT
                </>
            ) : (
                <>
                    <RefreshCw size={16} /> RECONSTRUCT
                </>
            )}
        </button>
      </div>

      {/* Loading State */}
      {loading && (
        <div className="absolute inset-0 flex items-center justify-center bg-black/40 backdrop-blur-[2px] pointer-events-auto">
          <div className="animate-spin text-luxury-gold">
            <Gem size={48} />
          </div>
          <p className="absolute mt-20 text-luxury-gold font-serif animate-pulse">Consulting the Elite...</p>
        </div>
      )}

      {/* Fortune Modal */}
      {fortune && !loading && (
        <div className="absolute inset-0 flex items-center justify-center pointer-events-auto bg-black/60 p-4">
          <div className="relative max-w-lg w-full bg-luxury-green border-4 border-luxury-gold p-1 shadow-2xl transform transition-all animate-in fade-in zoom-in duration-300">
            <div className="absolute inset-0 border border-white/20 m-1 pointer-events-none"></div>
            
            <button 
              onClick={onClose}
              className="absolute top-4 right-4 text-luxury-gold hover:text-white transition-colors"
            >
              <X size={24} />
            </button>

            <div className="p-8 text-center">
              <div className="mb-4 flex justify-center text-luxury-gold">
                <Sparkles size={32} />
              </div>
              
              <h3 className="font-serif text-luxury-gold-light text-xl mb-2 uppercase tracking-widest">
                {fortune.theme}
              </h3>
              
              <div className="h-px w-24 bg-gradient-to-r from-transparent via-luxury-gold to-transparent mx-auto mb-6"></div>
              
              <p className="font-serif text-2xl text-white leading-relaxed italic">
                "{fortune.message}"
              </p>
              
              <div className="mt-8 pt-4 border-t border-white/10">
                <p className="text-luxury-gold text-xs uppercase tracking-widest">
                  Official 2024 Prediction
                </p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};